version: '3'

services:
  orchestrator:
    container_name: saga-orchestrator
    build:
      context: .
      dockerfile: orchestrator/Dockerfile
    depends_on:
      - payments-ms
      - inventory-ms

  payments-ms:
    container_name: saga-payments-ms
    build:
      context: .
      dockerfile: payments/Dockerfile
    ports:
      - "4041:4041"

  inventory-ms:
    container_name: saga-inventory-ms
    build:
      context: .
      dockerfile: inventory/Dockerfile
    ports:
      - "4042:4042"